# -*- coding: utf-8 -*-
"""ERIS_TEST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pigm5jPeL2Ei4c67-KaKJJR1ayCeVYWJ
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf

# Load the TensorBoard notebook extension (optional)
# %load_ext tensorboard

tf.random.set_seed(42)
tf.__version__

print('SUCCESS TESNSOR')

INPUT_SHAPE = (50,50, 3)
vgg = tf.keras.applications.vgg19.VGG19(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)

vgg.trainable = False
# Freeze the layers
for layer in vgg.layers:
    layer.trainable = False

print('VGG SUCCESS')

